### ISSUE TITLE
Add Authentication in frontend

### ISSUE THREAD

**Issue by LordHarsh** [LordHarsh/movies-review#3]
## Tasks
- [ ] Create Login Page
- [ ] Create Signup Page
- [ ] Create Watchlist Page
- [ ] Refactor the Review Page
- [ ] Add alerts component
- [ ] Change the springboot response to include user data and success/failuire message
