### ISSUE TITLE
Add search features

### ISSUE THREAD

**Issue by LordHarsh** [LordHarsh/movies-review#5]
# Add a feature to search for movies using phrases:

## Tasks:
- [ ] Add controller function in user controllers in the spring-boot backend
- [ ] Add service function in user service in the spring-boot backend
- [ ] Add a search page and use movieCard component in the React frontend
- [ ] Add search route
- [ ] While reusing movieCard component, remove the delete button.
- [ ] Start using an environment variable for backend URL.
